//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS_Taxi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Shipping = new HashSet<Shipping>();
        }
    
        public int IdCar { get; set; }
        public string NumberCar { get; set; }
        public System.DateTime DateMade { get; set; }
        public int IDDriver { get; set; }
        public string Brand { get; set; }
        public string Carrying { get; set; }
        public string SpecEquipment { get; set; }

        public string DRIVER { get => $"{Driver.LName} {Driver.FName} {Driver.Patronymic}"; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping> Shipping { get; set; }
    }
}
