//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS_Taxi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int IdShipping { get; set; }
        public System.DateTime DateTime { get; set; }
        public int IDClient { get; set; }
        public int IDWorker { get; set; }
        public int IDTarrif { get; set; }
        public int IDCar { get; set; }
        public int Mileage { get; set; }
        public string OtherTerms { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
